### ISSUE TITLE
[Windows][Conan] Conan errors out whilst trying to create vs solution

### ISSUE THREAD

**Issue by tunip3** [rwengine/openrw#738]
```CMake Error at external/imgui/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    imgui/imgui.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at external/imgui/CMakeLists.txt:35 (add_library):
  Cannot find source file:

    imgui/examples/imgui_impl_opengl3.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at external/imgui/CMakeLists.txt:1 (add_library):
  No SOURCES given to target: imgui


CMake Error at external/imgui/CMakeLists.txt:35 (add_library):
  No SOURCES given to target: imgui_sdl_gl3


CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "scripts/conan/create_vs_solution.py", line 72, in <module>
    main()
  File "scripts/conan/create_vs_solution.py", line 68, in main
    create_solution(path=path, vs_version=vs_version, arch=arch)
  File "scripts/conan/create_vs_solution.py", line 39, in create_solution
    subprocess.run([
  File "C:\Users\t3\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-DUSE_CONAN=ON', '-DBOOST_STATIC=ON', '-DMSVC_NO_DEBUG_RUNTIME=ON', '-DBUILD_TESTS=ON', '-DBUILD_VIEWER=ON', '-DBUILD_TOOLS=ON', '-GVisual Studio 15 2017 Win64', 'D:\\Xboxone\\ports\\fuckyoutux\\openrw-master']' returned non-zero exit status 1```

this occurs when running the command `python scripts/conan/create_vs_solution.py -v 2017 -a x64 D:\Xboxone\ports\fuckyoutux\deathtolinux`

Any help would be greatly appreciated. 

(sidenote the directory names are a dig at a friend rather than being originated from an actual disdain for Linux)

**Comment by dracc** [comment]
Looks like you've forgotten to initialize submodules.
Try running `git submodule update --init --recursive` from inside your `openrw` directory. :)

**Comment by tunip3** [comment]
thanks this solved it
