### ISSUE TITLE
Illegal Instruction 03d4 encountered at offset 17b77 on thread IMPORT1

### ISSUE THREAD

**Issue by gbudny** [rwengine/openrw#90]
Hi

The game crashed in this area:

https://www.youtube.com/watch?v=CHIPqOA6fx0

1:12

 ./rwgame
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
Created: version = 3.3 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
I [Game] Game directory: /home/gbudny/GTAIII
Max UBO Size: 65536
UBO Alignment: 256
Max batch size: 512
I [Renderer] OpenGL Renderer Version: 3.3.0 NVIDIA 340.96 (GLSL 3.30 NVIDIA via Cg compiler) Vendor: NVIDIA Corporation
I [Data] Loaded 42 zones from /home/gbudny/GTAIII/data/gta3.zon
I [Game] Started
Fstat failed ()
I [World] Loaded cutscene: BET
Fstat failed ()
I [World] Loaded cutscene: JB
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 117 (ENFORCR)
I [World] Creating Vehicle ID 130 (RUMPO)
I [World] Creating Vehicle ID 96 (PATRIOT)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 116 (POLICAR)
Fstat failed ()
I [World] Loaded cutscene: L1_LG
Fstat failed ()
I [World] Loaded cutscene: L2_DSB
I [World] Creating Vehicle ID 129 (STALION)
Illegal Instruction 03d4 encountered at offset 17b77 on thread IMPORT1
E [Script] Illegal Instruction 03d4 encountered at offset 17b77 on thread IMPORT1
terminate called after throwing an instance of 'IllegalInstruction'
Aborted (core dumped)

**Comment by gbudny** [comment]
gdb ./rwgame
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./rwgame...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/gbudny/Desktop/openrw-build/rwgame/rwgame 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffefa54700 (LWP 1963)]
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 1.1 ; depth bits = 32 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
Created: version = 3.3 ; depth bits = 24 ; stencil bits = 8 ; AA level = 0 ; core = false ; debug = false
I [Game] Game directory: /home/gbudny/GTAIII
Max UBO Size: 65536
UBO Alignment: 256
Max batch size: 512
I [Renderer] OpenGL Renderer Version: 3.3.0 NVIDIA 340.96 (GLSL 3.30 NVIDIA via Cg compiler) Vendor: NVIDIA Corporation
[New Thread 0x7fffeb6ec700 (LWP 1965)]
[New Thread 0x7fffeb6ec700 (LWP 1966)]
[Thread 0x7fffeb6ec700 (LWP 1965) exited]
[New Thread 0x7fffe6eea700 (LWP 1967)]
I [Data] Loaded 42 zones from /home/gbudny/GTAIII/data/gta3.zon
I [Game] Started
Fstat failed ()
[New Thread 0x7fffe67b3700 (LWP 1968)]
I [World] Loaded cutscene: BET
libmad error: lost synchronization
[Thread 0x7fffe67b3700 (LWP 1968) exited]
Fstat failed ()
[New Thread 0x7fffe4cab700 (LWP 1973)]
I [World] Loaded cutscene: JB
libmad error: lost synchronization
[Thread 0x7fffe4cab700 (LWP 1973) exited]
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 117 (ENFORCR)
I [World] Creating Vehicle ID 130 (RUMPO)
I [World] Creating Vehicle ID 96 (PATRIOT)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 105 (CHEETAH)
I [World] Creating Vehicle ID 92 (STINGER)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 110 (TAXI)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 111 (KURUMA)
I [World] Creating Vehicle ID 116 (POLICAR)
I [World] Creating Vehicle ID 116 (POLICAR)
Fstat failed ()
[New Thread 0x7fffdb4f0700 (LWP 2354)]
I [World] Loaded cutscene: L1_LG
libmad error: lost synchronization
[Thread 0x7fffdb4f0700 (LWP 2354) exited]
Fstat failed ()
[New Thread 0x7fffda741700 (LWP 2366)]
I [World] Loaded cutscene: L2_DSB
libmad error: lost synchronization
[Thread 0x7fffda741700 (LWP 2366) exited]
I [World] Creating Vehicle ID 129 (STALION)
Illegal Instruction 03d4 encountered at offset 17b77 on thread IMPORT1
E [Script] Illegal Instruction 03d4 encountered at offset 17b77 on thread IMPORT1
terminate called after throwing an instance of 'IllegalInstruction'

Thread 1 "rwgame" received signal SIGABRT, Aborted.
0x00007ffff54d9418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff54d9418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff54db01a in __GI_abort () at abort.c:89
#2  0x00007ffff603884d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff60366b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6036701 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6036969 in __cxa_rethrow ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000448421 in RWGame::tick(float) ()
#7  0x000000000044b93d in RWGame::run() ()
#8  0x000000000043e010 in main ()
